//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacjenci
    {
        public int id_pacjenta { get; set; }
        public string nazwisko { get; set; }
        public string imie { get; set; }
        public string pesel { get; set; }
        public System.DateTime data_przyjecia { get; set; }
        public Nullable<System.DateTime> data_urodzenia { get; set; }
        public string plec { get; set; }
        public string nr_pokoju { get; set; }
        public string choroba { get; set; }
    
        public virtual pokoje pokoje { get; set; }
    }
}
